import { CodegenObjectSchema } from '@openapi-generator-plus/types/src/types';
import { CGCodegenNamedSchema, CLI, XImports } from '~/types';
import { addImport } from '~/utils/vendorExtensions';
import { processExtraAnnotations, processXTsType } from './actions';
import { isClient } from '~/utils/generatorType';

/**
 * Processes all the vendor extensions, ie x-ts-*
 *
 * x-ts-type: hardcoded type which means this file should not be generated
 * x-ts-imports: list of imports to provide for this schema
 */
const process = (
  schema: CGCodegenNamedSchema,
  child?: CGCodegenNamedSchema,
) => {
  if (schema.type === 'object') {
    processExtraAnnotations(schema as unknown as CodegenObjectSchema);
  }

  // This is hardcoded type, which means we should ignore it
  // However, it also means we need to import it, so add it to the list of imports
  if (schema.vendorExtensions?.['x-ts-type']) {
    if (isClient()) {
      schema.vendorExtensions['x-ts-type'] = schema.vendorExtensions[
        'x-ts-type'
      ].replace('@2025-personal-portfolio/common/dist', '@2025-personal-portfolio/common/src');
    }
    processXTsType(schema, child);
  }
  // Add the autogenerated schema as an import
  else if (schema.scopedName !== null) {
    const item: XImports = {
      path: `./${schema.name}`,
      name: schema.name
    };

    // addImport(schema.vendorExtensions, item);
    if (child) {
      addImport(child.vendorExtensions, item);
    }
  }

  if (schema.composes?.length) {
    schema.composes.forEach((s) => {
      const name = s.component?.schema?.name;
      if (name) {
        const item: XImports = {
          path: `./${name}`,
          name,
        };
        addImport(schema.vendorExtensions, item);
      }
    });
  }

  // schema?.discriminatorValues?.forEach((discriminator) => {
  //   const name = discriminator.literalValue.split('.')[0];
  //   const item: XImports = {
  //     path: `./${name}`,
  //     name,
  //   };
  //   addImport(schema.vendorExtensions, item);
  // });

  if (schema.discriminator) {
    // This means there will be a plural version of this.
    // so let's also add that as an import
    const item: XImports = {
      path: `./${schema.name}s`,
      name: `${schema.name}s`,
    };
    addImport(schema.vendorExtensions, item);
  }
};

/**
 * Processes each {@link CGCodegenNamedSchema}
 */
const processSchema = (cli: CLI, schema: CGCodegenNamedSchema) => {
  process(schema);
  if (schema.type === 'object') {
    (schema as unknown as CodegenObjectSchema).parents?.map((p) =>
      process(p as unknown as CGCodegenNamedSchema, schema),
    );
  }

  if (schema?.composes?.length) {
    schema.composes.forEach((s) => {
      process(s as unknown as CGCodegenNamedSchema, schema);
    });
  }
};

export default processSchema;
